# Generated by Django 3.2.12 on 2022-04-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
