# Generated by Django 3.2.12 on 2022-04-09 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_task_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='name',
        ),
    ]
