# Generated by Django 3.2.12 on 2022-04-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_rename_task_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1993-04-21'),
            preserve_default=False,
        ),
    ]
